# Generated by Django 5.1.7 on 2025-03-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='object',
            new_name='object_file',
        ),
    ]
