# Generated by Django 5.1.7 on 2025-03-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0006_counter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counter',
            new_name='Count',
        ),
        migrations.RenameField(
            model_name='count',
            old_name='counter',
            new_name='count',
        ),
    ]
