# Generated by Django 5.1.7 on 2025-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0007_rename_counter_count_rename_counter_count_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
