# Generated by Django 5.1.7 on 2025-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0008_count_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.CharField(blank=True, default='blank', max_length=200, null=True),
        ),
    ]
