# Generated by Django 5.1.7 on 2025-03-29 19:16

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0009_alter_count_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('electric', 'elektryczny'), ('petrol', 'benzyna'), ('diesel', 'diesel')], max_length=22),
        ),
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
