# Generated by Django 5.1.7 on 2025-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0011_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eq-images/'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car-images/'),
        ),
    ]
