# Generated by Django 5.1.7 on 2025-04-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0013_calendars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendars',
        ),
    ]
