# Generated by Django 5.1.7 on 2025-04-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarShowroom', '0015_calendars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendars',
            old_name='data',
            new_name='date',
        ),
    ]
